name: The Changes
favicon: null
layout_spectrum: 0.4515606318600476
typography_spectrum: 0.6788077175151557
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9331348766572773
  lightness: 0.35346500063315034
  saturation: 0.042980768252164125
  rhythmicContrast: 0.8238099797163159
purpose: []
